# fly.toml app configuration file generated for gossyp-api on 2023-12-07T04:17:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gossyp-api"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
